export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_APPLICATIONS = "GET_APPLICATIONS";
export const CREATE_APPLICATION = "CREATE_APPLICATIONS";
export const UPDATE_APPLICATION_STATUS = "UPDATE_APPLICATION_STATUS";